
name: 'Git Operations'
description: 'Configure Git, commit changes, and push tags'
inputs:
  version:
    description: 'Version to tag'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Configure Git
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Commit version changes
      shell: bash
      run: |
        git add public/version.json
        git commit -m "chore(release): bump version to ${{ inputs.version }}"
        git tag "v${{ inputs.version }}"

    - name: Push changes
      shell: bash
      run: |
        git push origin main
        git push origin "v${{ inputs.version }}"
