
name: 'Setup Dependencies and Security Check'
description: 'Install dependencies, fix vulnerabilities, and run security audit'
inputs:
  skip_tests:
    description: 'Skip tests during setup'
    required: false
    default: 'false'
outputs:
  security_passed:
    description: 'Whether security check passed'
    value: ${{ steps.security-check.outputs.passed }}
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm install

    - name: Auto-fix security vulnerabilities
      shell: bash
      run: |
        echo "Attempting to auto-fix security vulnerabilities before release..."
        npm audit fix --audit-level=high || echo "Some vulnerabilities couldn't be auto-fixed"

    - name: Run tests
      if: ${{ inputs.skip_tests == 'false' }}
      shell: bash
      run: npx vitest run

    - name: Security check (high/critical only)
      id: security-check
      shell: bash
      run: |
        AUDIT_RESULT=$(npm audit --audit-level=high --json || echo '{}')
        HIGH_CRITICAL_COUNT=$(echo "$AUDIT_RESULT" | jq -r '.metadata.vulnerabilities.high + .metadata.vulnerabilities.critical // 0' 2>/dev/null || echo "0")
        
        if [ "$HIGH_CRITICAL_COUNT" -gt 0 ]; then
          echo "❌ Cannot release with high/critical vulnerabilities"
          npm audit --audit-level=high
          echo "passed=false" >> $GITHUB_OUTPUT
          exit 1
        fi
        echo "passed=true" >> $GITHUB_OUTPUT

    - name: Build project
      shell: bash
      run: npm run build
