name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
  # Also run when the Auto Release workflow completes successfully. This covers
  # the case where the auto-release job creates a commit (with a token) that
  # otherwise wouldn't trigger subsequent workflows.
  workflow_run:
    workflows: ["Auto Release"]
    types:
      - completed

# Allow one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

permissions:
  contents: read
  pages: write      # to deploy to Pages
  id-token: write   # to verify the deployment originates from an appropriate source

jobs:
  build:
    name: Build site
    # Only run the build job on a direct push to main, or when the Auto Release
    # workflow completes successfully. This avoids rerunning for failed
    # auto-release executions.
    if: "${{ github.event_name == 'push' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.1.0
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Build (custom domain)
        run: |
          # Custom domain build (root path)
            npx vite build --base=/
            # Add .nojekyll
            touch dist/.nojekyll
            # Ensure CNAME present
            cp public/CNAME dist/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    name: Deploy
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
